/*
# Oakland Motors core operations schema

1. Purpose
- Creates the core authenticated staff, customer, vehicle, workshop, inventory, billing, payment, notification, and audit tables.
- Stores all KES money as integer minor units and uses UUID keys.

2. Security
- Enables RLS on every business table.
- Uses `has_permission` to enforce staff access in the database.
- Adds safe defaults for authenticated actors and timestamps.

3. Multi-branch readiness
- Core operational tables include nullable `branch_id` for future branches.
*/
create extension if not exists pgcrypto;
create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
create table if not exists public.roles(id uuid primary key default gen_random_uuid(),name text unique not null,label text not null,created_at timestamptz not null default now());
create table if not exists public.permissions(id uuid primary key default gen_random_uuid(),key text unique not null,label text not null,created_at timestamptz not null default now());
create table if not exists public.role_permissions(role_id uuid not null references public.roles(id) on delete cascade,permission_id uuid not null references public.permissions(id) on delete cascade,primary key(role_id,permission_id));
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',phone text,job_title text,avatar_url text,branch_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.user_roles(user_id uuid not null references auth.users(id) on delete cascade,role_id uuid not null references public.roles(id) on delete cascade,primary key(user_id,role_id));
create or replace function public.has_permission(permission_key text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id left join public.role_permissions rp on rp.role_id=r.id left join public.permissions p on p.id=rp.permission_id where ur.user_id=auth.uid() and (r.name='ADMIN' or p.key=permission_key)); $$;
create table if not exists public.customers(id uuid primary key default gen_random_uuid(),branch_id uuid,full_name text not null,company_name text,customer_type text not null default 'INDIVIDUAL' check(customer_type in('INDIVIDUAL','COMPANY')),phone text not null,alternative_phone text,email text,address text,notes text,status text not null default 'ACTIVE' check(status in('ACTIVE','ARCHIVED')),created_by uuid default auth.uid() references auth.users(id),updated_by uuid default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists public.vehicles(id uuid primary key default gen_random_uuid(),branch_id uuid,customer_id uuid not null references public.customers(id),registration_number text not null,make text not null,model text not null,year integer check(year is null or year between 1950 and 2100),vin text,mileage integer not null default 0 check(mileage>=0),colour text,engine_number text,fuel_type text,transmission text,notes text,created_by uuid default auth.uid() references auth.users(id),updated_by uuid default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists public.services(id uuid primary key default gen_random_uuid(),name text not null,category text not null default 'General',description text,standard_price_minor integer not null default 0 check(standard_price_minor>=0),estimated_minutes integer not null default 60 check(estimated_minutes>0),tax_rate numeric(5,2) not null default 16 check(tax_rate between 0 and 100),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.parts(id uuid primary key default gen_random_uuid(),branch_id uuid,sku text not null,name text not null,category text not null default 'General',brand text,cost_price_minor integer not null default 0 check(cost_price_minor>=0),selling_price_minor integer not null default 0 check(selling_price_minor>=0),quantity_on_hand integer not null default 0 check(quantity_on_hand>=0),reorder_level integer not null default 0 check(reorder_level>=0),location text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(branch_id,sku));
create table if not exists public.job_cards(id uuid primary key default gen_random_uuid(),branch_id uuid,job_number text unique not null,customer_id uuid not null references public.customers(id),vehicle_id uuid not null references public.vehicles(id),mileage integer not null default 0 check(mileage>=0),complaint text not null,requested_service text,diagnosis text,recommended_work text,priority text not null default 'NORMAL' check(priority in('LOW','NORMAL','HIGH','URGENT')),status text not null default 'RECEIVED' check(status in('RECEIVED','DIAGNOSING','AWAITING_APPROVAL','IN_PROGRESS','AWAITING_PARTS','COMPLETED','READY_FOR_PICKUP','DELIVERED','CANCELLED')),estimated_completion_date date,created_by uuid default auth.uid() references auth.users(id),updated_by uuid default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists public.job_card_assignments(id uuid primary key default gen_random_uuid(),job_card_id uuid not null references public.job_cards(id) on delete cascade,technician_id uuid not null references auth.users(id),assigned_by uuid default auth.uid() references auth.users(id),assigned_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.job_card_labour(id uuid primary key default gen_random_uuid(),job_card_id uuid not null references public.job_cards(id) on delete cascade,service_id uuid references public.services(id),description text not null,quantity numeric(10,2) not null default 1 check(quantity>0),unit_price_minor integer not null default 0 check(unit_price_minor>=0),tax_rate numeric(5,2) not null default 16 check(tax_rate between 0 and 100),created_at timestamptz not null default now());
create table if not exists public.job_card_parts(id uuid primary key default gen_random_uuid(),job_card_id uuid not null references public.job_cards(id) on delete cascade,part_id uuid not null references public.parts(id),quantity integer not null check(quantity>0),unit_price_minor integer not null default 0 check(unit_price_minor>=0),issued_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.job_card_status_history(id uuid primary key default gen_random_uuid(),job_card_id uuid not null references public.job_cards(id) on delete cascade,from_status text,to_status text not null,changed_by uuid default auth.uid() references auth.users(id),changed_at timestamptz not null default now());
create table if not exists public.invoices(id uuid primary key default gen_random_uuid(),branch_id uuid,invoice_number text unique not null,customer_id uuid not null references public.customers(id),vehicle_id uuid references public.vehicles(id),job_card_id uuid references public.job_cards(id),subtotal_minor integer not null default 0 check(subtotal_minor>=0),discount_minor integer not null default 0 check(discount_minor>=0),tax_minor integer not null default 0 check(tax_minor>=0),total_minor integer not null default 0 check(total_minor>=0),amount_paid_minor integer not null default 0 check(amount_paid_minor>=0 and amount_paid_minor<=total_minor),due_date date,status text not null default 'DRAFT' check(status in('DRAFT','ISSUED','PART_PAID','PAID','OVERDUE','VOID')),created_by uuid default auth.uid() references auth.users(id),updated_by uuid default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.invoices(id) on delete cascade,item_type text not null check(item_type in('LABOUR','PART','OTHER')),description text not null,quantity numeric(10,2) not null default 1 check(quantity>0),unit_price_minor integer not null default 0 check(unit_price_minor>=0),tax_rate numeric(5,2) not null default 16 check(tax_rate between 0 and 100),line_total_minor integer not null default 0 check(line_total_minor>=0),created_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.invoices(id),amount_minor integer not null check(amount_minor>0),method text not null check(method in('CASH','MPESA','BANK','CARD','OTHER')),reference text,paid_at timestamptz not null default now(),recorded_by uuid default auth.uid() references auth.users(id),notes text,idempotency_key text unique,created_at timestamptz not null default now());
create table if not exists public.mpesa_transactions(id uuid primary key default gen_random_uuid(),invoice_id uuid references public.invoices(id),merchant_request_id text unique,checkout_request_id text unique,receipt_number text,phone_number text not null,amount_minor integer not null check(amount_minor>0),result_code integer,result_description text,status text not null default 'PENDING' check(status in('PENDING','SUCCESS','FAILED')),raw_callback jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,message text not null,type text not null default 'INFO',read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid default auth.uid() references auth.users(id),action text not null,entity text not null,entity_id uuid,before_state jsonb,after_state jsonb,metadata jsonb,created_at timestamptz not null default now());
create index if not exists customers_phone_idx on public.customers(phone); create index if not exists customers_name_idx on public.customers(lower(full_name)); create index if not exists vehicles_registration_idx on public.vehicles(lower(registration_number)); create index if not exists vehicles_vin_idx on public.vehicles(vin); create index if not exists job_cards_status_idx on public.job_cards(status); create index if not exists job_cards_created_idx on public.job_cards(created_at desc); create index if not exists parts_sku_idx on public.parts(lower(sku)); create index if not exists parts_name_idx on public.parts(lower(name)); create index if not exists invoices_status_idx on public.invoices(status); create index if not exists payments_reference_idx on public.payments(reference); create unique index if not exists vehicles_registration_unique_idx on public.vehicles(lower(registration_number)) where deleted_at is null;
create trigger customers_touch_updated_at before update on public.customers for each row execute function public.touch_updated_at(); create trigger vehicles_touch_updated_at before update on public.vehicles for each row execute function public.touch_updated_at(); create trigger services_touch_updated_at before update on public.services for each row execute function public.touch_updated_at(); create trigger parts_touch_updated_at before update on public.parts for each row execute function public.touch_updated_at(); create trigger job_cards_touch_updated_at before update on public.job_cards for each row execute function public.touch_updated_at(); create trigger invoices_touch_updated_at before update on public.invoices for each row execute function public.touch_updated_at(); create trigger mpesa_touch_updated_at before update on public.mpesa_transactions for each row execute function public.touch_updated_at();
alter table public.roles enable row level security; alter table public.permissions enable row level security; alter table public.role_permissions enable row level security; alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.customers enable row level security; alter table public.vehicles enable row level security; alter table public.services enable row level security; alter table public.parts enable row level security; alter table public.job_cards enable row level security; alter table public.job_card_assignments enable row level security; alter table public.job_card_labour enable row level security; alter table public.job_card_parts enable row level security; alter table public.job_card_status_history enable row level security; alter table public.invoices enable row level security; alter table public.invoice_items enable row level security; alter table public.payments enable row level security; alter table public.mpesa_transactions enable row level security; alter table public.notifications enable row level security; alter table public.audit_logs enable row level security;
do $$ declare t text; begin foreach t in array array['profiles','customers','vehicles','services','parts','job_cards','job_card_assignments','job_card_labour','job_card_parts','job_card_status_history','invoices','invoice_items','payments','mpesa_transactions','notifications','audit_logs'] loop execute format('drop policy if exists "staff_select_%1$s" on public.%1$s',t); execute format('drop policy if exists "staff_insert_%1$s" on public.%1$s',t); execute format('drop policy if exists "staff_update_%1$s" on public.%1$s',t); execute format('drop policy if exists "staff_delete_%1$s" on public.%1$s',t); execute format('create policy "staff_select_%1$s" on public.%1$s for select to authenticated using(public.has_permission(''dashboard.view''))',t); execute format('create policy "staff_insert_%1$s" on public.%1$s for insert to authenticated with check(public.has_permission(''dashboard.view''))',t); execute format('create policy "staff_update_%1$s" on public.%1$s for update to authenticated using(public.has_permission(''dashboard.view'')) with check(public.has_permission(''dashboard.view''))',t); execute format('create policy "staff_delete_%1$s" on public.%1$s for delete to authenticated using(public.has_permission(''settings.manage''))',t); end loop; end $$;
create policy "staff_select_roles" on public.roles for select to authenticated using(public.has_permission('dashboard.view')); create policy "staff_select_permissions" on public.permissions for select to authenticated using(public.has_permission('dashboard.view')); create policy "staff_select_role_permissions" on public.role_permissions for select to authenticated using(public.has_permission('dashboard.view')); create policy "staff_select_user_roles" on public.user_roles for select to authenticated using(public.has_permission('settings.manage'));
insert into public.roles(name,label) values('ADMIN','Administrator'),('MANAGER','Garage Manager'),('SERVICE_ADVISOR','Service Advisor'),('TECHNICIAN','Technician'),('STOREKEEPER','Storekeeper'),('ACCOUNTANT','Accountant'),('OWNER_READONLY','Owner') on conflict(name) do nothing;
insert into public.permissions(key,label) values('dashboard.view','View dashboard'),('customer.view','View customers'),('customer.create','Create customers'),('customer.update','Update customers'),('vehicle.view','View vehicles'),('vehicle.create','Create vehicles'),('job.view','View job cards'),('job.create','Create job cards'),('job.update','Update job cards'),('job.assign','Assign technicians'),('job.complete','Complete jobs'),('inventory.view','View inventory'),('inventory.issue','Issue parts'),('inventory.receive','Receive stock'),('inventory.adjust','Adjust stock'),('quotation.create','Create quotations'),('quotation.approve','Approve quotations'),('invoice.create','Create invoices'),('invoice.update','Update invoices'),('payment.create','Record payments'),('payment.view','View payments'),('report.view','View reports'),('report.export','Export reports'),('audit.view','View audit logs'),('settings.manage','Manage settings') on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.name<>'OWNER_READONLY' on conflict do nothing; insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in('dashboard.view','report.view','report.export') where r.name='OWNER_READONLY' on conflict do nothing;
revoke all on function public.has_permission(text) from public; grant execute on function public.has_permission(text) to authenticated;